language: python
before_script:
- pip install tox
- pip install -U requests"$REQUESTS_VERSION"

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

env:
  global:
  - TRAVIS_GH3="True"
  matrix:
  - TOXENV=py26 REQUESTS_VERSION="===2.0.1"
  - TOXENV=py27 REQUESTS_VERSION="===2.0.1"
  - TOXENV=py32 REQUESTS_VERSION="===2.0.1"
  - TOXENV=py33 REQUESTS_VERSION="===2.0.1"
  - TOXENV=py34 REQUESTS_VERSION="===2.0.1"
  - TOXENV=pypy REQUESTS_VERSION="===2.0.1"
  - TOXENV=py26 REQUESTS_VERSION=""
  - TOXENV=py27 REQUESTS_VERSION=""
  - TOXENV=py32 REQUESTS_VERSION=""
  - TOXENV=py33 REQUESTS_VERSION=""
  - TOXENV=py34 REQUESTS_VERSION=""
  - TOXENV=pypy REQUESTS_VERSION=""
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8
  - TOXENV=docstrings
  - TOXENV=notebooks

matrix:
  fast_finish: true
  allow_failures:
  - env: TOXENV=docstrings
  - env: TOXENV=notebooks

sudo: false
